name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]
    branches: [main]
  workflow_dispatch:

jobs:
  deployment:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' }}
    permissions:
      contents: read
    uses: jaudiger/reusable-workflows/.github/workflows/deploy-zine-cloudflare-pages.yml@eeb6e74f96a49785e3a1879d8797b75fbce9a43d
    with:
      zine-version: "v0.11.2"
      output-dir: "public"
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
